spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 20MB

springdoc:
#  show-actuator: true
#  use-management-port: true
  swagger-ui:
    path: /docs.html
#    enabled: false
  api-docs:
    path: /api/docs.yaml
#    enabled: false

# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
#management:
#  endpoints.web.exposure.include: openapi, swagger-ui, health, metrics, prometheus, env, beans
#  server:
#    port: 9090