version: '3.3'
services:
  app:
#    build:
#      context: .
    image: docker.io/library/spring-boot-rest:1.0.0
    container_name: spring_new
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tms
      - SPRING_DATASOURCE_USERNAME=tms
      - SPRING_DATASOURCE_PASSWORD=qwerty
    depends_on:
      - db
    ports:
      - '8081:8081'

  db:
#    platform: linux/x86_64
#    image: postgres:14-alpine
    image: nexus-ci.corp.dev.vtb/pfomb-docker/postgres:15.3
    container_name: postgres_14
    restart: always
    environment:
      - POSTGRES_DB=tms
      - POSTGRES_USER=tms
      - POSTGRES_PASSWORD=qwerty
#    ports:
#      - '5432:5432'
    volumes:
      - ./new-postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'

  mysql:
    image: mysql:8.0.20
    container_name: mysql_8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  new-postgres-data: